
  vr.tcp_client = comm.tcp.initialize_tcp( ...
      '192.168.0.22', ...
      RigParameters.tcpClientPort, ...
      'client', ...
      40);
  
  
virmen_structures = comm.virmen_specific.get_all_virmen_vars(tcp_client, codes_files, virmen_structure);

